[package]
name = "stump"
version = "0.1.0"
edition = "2021"
default-run = "stump"

[dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.5.0" }
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
# env_logger = "0.9.0"
rocket =  { version = "0.5.0-rc.2", features =  ["json" ] }
# rocket-session-store = "0.2.0"
# rocket-session-store = { path = "../../../../../Documents/sandbox/clones/rocket-session-store", features = ["okapi"] }
rocket-session-store = { git = "https://github.com/aaronleopold/rocket-session-store", branch = "develop", features = ["okapi"] }
rocket_cors = "0.6.0-alpha1"
bcrypt = "0.10.1"
anyhow = "1.0.57"
xml-rs = "0.8.4"
serde-xml-rs = "0.5.1"
urlencoding = "2.1.0"
thiserror = "1.0.30"
base64 = "0.13.0"
log = "0.4.0"
epub = "1.2.3"
walkdir = "2.3.2"
zip = "0.5.13"
# unrar = "0.4.4"
unrar = { git = "https://github.com/aaronleopold/unrar.rs", branch = "aleopold--read-bytes" }
async-trait = "0.1.53"
infer = "0.7.0"
dirs = "4.0.0"

# Using clap to make the seed more configurable
clap = { version = "3.1.18", features = ["derive"], optional = true }
ring = "0.16.20"
data-encoding = "2.3.2"
cuid = "1.2.0"
webp = "0.2.2"
image = "0.24.2"
include_dir = "0.7.2"
# TODO: make this *NOT* bundled in release, not necessary. I guess I would have to feature
# gate it? but that is just kinda annoying. Since I am pushing this feature off for now, 
# hopefully the PR branch I am pointing to is merged, as well.
rocket_okapi = { git = "https://github.com/ThouCheese/okapi", branch = "feat/rocket0.5-rc.2", features = ["rapidoc", "swagger"] }
schemars = "0.8.10"

[features]
seed-binary = ["clap"]

[[bin]]         
name = "seed"    
required-features = ["seed-binary"] 
